### ISSUE TITLE
Saving file after update_header

### ISSUE THREAD

**Issue by pmaggiore** [tmontaigu/pylas#13]
Hi,
I'm trying to write the file with the same name after I apply the update_header(), but I'm getting "Permission Denied". It happens even if I close the file.

I tried to check the documentation but I can't find a way to save the file after the update_header using the same name. Am I forced to write to another file name?

I hope you can help,

pm

**Comment by pmaggiore** [comment]
Ok, I'm closing this; it is possible to write the file with the same name. I was just having problems not related with pylas.

pm

**Comment by tmontaigu** [comment]
And update_header is automatically called when you write the file

**Comment by pmaggiore** [comment]
Ah nice, thank you for the info!

pm
