### ISSUE TITLE
Helper to write SRS as WKT in VLR format

### ISSUE THREAD

**Issue by RomainLaporte** [tmontaigu/pylas#31]
Hi,
First, thank you for this very helpful library.
Is there any way to easily write the SRS in WKT format when creating a las file with pylas.create() ?
I see there is a write_to() method from the pylas.vlrs.vlrlist module but I do not understand how it works. Maybe an example can help here.
Thanks.

**Comment by tmontaigu** [comment]
Hello you shoud be able to add a a Wkt a VLR to a las object by doing:

```python
>>> import pylas
>>> las = pylas.create()
>>> wkt_vlr = pylas.vlrs.known.WktCoordinateSystemVlr(some_wkt_str)
>>> las.vlrs.append(wkt_vlr)
>>> las.write("test.las") # The resulting las should have the wkt saved

```

However this is defined only for LAS version >= 1.4

**Comment by RomainLaporte** [comment]
Thank you, that's exactly what I was looking for !
