### ISSUE TITLE
Make `pylas.open` more pythonic

### ISSUE THREAD

**Issue by mccarthyryanc** [tmontaigu/pylas#5]
This might be a tough request, but it would be nice to be able to separate out the current `open` function into more pythonic `open` and `read` functions. For example:
```python
with pylas.open('simple.laz') as fh:
    fh.read()
```
Having `pylas.open` read into the file/handle/stream enough just to get the header, would also provide convenient/quick access to some info without reading the entire dataset.

**Comment by tmontaigu** [comment]
Well, I planned on renaming the open function as it's a terrible name for a function that actually reads the content.

As for the ability to have a open function that would then allow to read certain par of the file, it can be done I'm exploring a way to to it, but I don't know how well it's going to end.

**Comment by tmontaigu** [comment]
I just merged a branch that makes pylas.open more pythonic.
pylas.open will now just read the header.
``` python
with pylas.open('simple.laz') as fh:
   print(fh.read_vlrs())
   if fh.header.number_of_point_records <10 ** 6:
       las = fh.read()

```

The old pylas.open (which was reading the whole file) is now named pylas.read

**Comment by mccarthyryanc** [comment]
Awesome! Thanks for the quick response on this! Constantly impressed with this module!
Just a question about the if block: is there a hard coded limit on the number points to read it?

**Comment by tmontaigu** [comment]
No, the block is just a small example of what you could do
